# Generated by Django 2.0.5 on 2018-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
