# Generated by Django 2.0.5 on 2018-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20180504_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement Station Game'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score', 'time'], 'verbose_name': 'Achievement Station Score'},
        ),
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
