# Generated by Django 2.0.5 on 2018-05-06 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20180504_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score - leave blank if time achievement'),
        ),
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Time - leave blank if high score achievement'),
        ),
    ]
