# Generated by Django 2.0.5 on 2018-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_auto_20180506_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Scheduled Date/Time'),
        ),
    ]
