# Generated by Django 2.0.5 on 2018-05-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_auto_20180506_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['event_time'], 'verbose_name': 'Achievement Station Game'},
        ),
    ]
