# Generated by Django 2.0.5 on 2018-05-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_auto_20180506_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
