# Generated by Django 2.0.5 on 2018-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0018_auto_20180508_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to='liretro/scoreboard/static/scoreboard/images/achgames'),
        ),
    ]
