# Generated by Django 2.0.5 on 2018-05-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0020_auto_20180508_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first+', to='scoreboard.Player', verbose_name='First Place Player/Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second+', to='scoreboard.Player', verbose_name='Second Place Player/Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third+', to='scoreboard.Player', verbose_name='Third Place Player/Team'),
        ),
    ]
